//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCG.siteTRAXLite.Common.Constants.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UCG.siteTRAXLite.Common.Constants.Localization.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later..
        /// </summary>
        internal static string APINotFoundContent {
            get {
                return ResourceManager.GetString("APINotFoundContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the siteTRAX service at this time..
        /// </summary>
        internal static string APINotFoundTitle {
            get {
                return ResourceManager.GetString("APINotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to st-lite-poc-config-v3.json.
        /// </summary>
        internal static string ConfigFileName {
            get {
                return ResourceManager.GetString("ConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configs.
        /// </summary>
        internal static string ConfigFolderName {
            get {
                return ResourceManager.GetString("ConfigFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string Error_BadRequest {
            get {
                return ResourceManager.GetString("Error_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error, Please check your network or endpoint setting..
        /// </summary>
        internal static string Error_ConnectionError {
            get {
                return ResourceManager.GetString("Error_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permission, please try again..
        /// </summary>
        internal static string Error_Permission {
            get {
                return ResourceManager.GetString("Error_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured in the server, please try again..
        /// </summary>
        internal static string Error_Server {
            get {
                return ResourceManager.GetString("Error_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api not found.
        /// </summary>
        internal static string Error_ServerNotFound {
            get {
                return ResourceManager.GetString("Error_ServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are error occurred, please try later..
        /// </summary>
        internal static string Error_SomeThingWrong {
            get {
                return ResourceManager.GetString("Error_SomeThingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session expired please login again.
        /// </summary>
        internal static string Error_Unauthorise {
            get {
                return ResourceManager.GetString("Error_Unauthorise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The api does not exist in server version.
        /// </summary>
        internal static string Error_WrongAPIVerion {
            get {
                return ResourceManager.GetString("Error_WrongAPIVerion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the form.
        /// </summary>
        internal static string Fill_The_Form {
            get {
                return ResourceManager.GetString("Fill_The_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogicPriceCode777.
        /// </summary>
        internal static string Logic_Price_Code_777 {
            get {
                return ResourceManager.GetString("Logic_Price_Code_777", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go to Setting page to correct endpoint..
        /// </summary>
        internal static string NoEndpointSelected {
            get {
                return ResourceManager.GetString("NoEndpointSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Endpoint is selected, please choose an endpoint..
        /// </summary>
        internal static string NoSelectedEndpoint {
            get {
                return ResourceManager.GetString("NoSelectedEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app is not installed on your device or can&apos;t open the app due to some error.
        /// </summary>
        internal static string Not_Installed_app {
            get {
                return ResourceManager.GetString("Not_Installed_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of meters of xxxxx?.
        /// </summary>
        internal static string Number_Of_Meters_Question {
            get {
                return ResourceManager.GetString("Number_Of_Meters_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com.ucg.sitetraxair.
        /// </summary>
        internal static string SiteTraxAir_Package_Name {
            get {
                return ResourceManager.GetString("SiteTraxAir_Package_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com.ucg.sitetraxair://launchapp.
        /// </summary>
        internal static string SiteTraxAir_Uri {
            get {
                return ResourceManager.GetString("SiteTraxAir_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted successfully.
        /// </summary>
        internal static string Submitted_Successfully {
            get {
                return ResourceManager.GetString("Submitted_Successfully", resourceCulture);
            }
        }
    }
}
